AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverlessly compute an md5sum of input
Resources:
  MD5SumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: md5sum/
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 3
      Events:
        MD5Sum:
          Type: HttpApi
          Properties:
            Path: /md5
            Method: get
